import Head from "next/head";
import { Inter } from "@next/font/google";

import { Header, Prizes, Card, Button, Badge, Typography } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Header />
        <Prizes />
        <Typography>NTO (NFT token offering) gives you a chance to get popular tokens 3-6 times cheaper from its market price in the form of exclusive NFT.</Typography>
        <Card>
          <Typography>
            Receive 3% royalty for every NFT reselling on the secondary market
          </Typography>
          
        </Card>
        <Badge>10000</Badge>
      </main>
    </>
  );
}
