import Head from "next/head";

import { Header, Footer } from "@/components";

import {
  LearnContainer,
  GoalsContainer,
  TeamContainer,
  PartnersContainer,
  FaqContainer,
  StatsContainer,
  CommunityContainer,
  PlansContainer,
  StagesContainer,
  MintContainer,
  UseContainer,
  RewardContainer,
  TryContainer,
  HistoryContainer,
  BadgesContainer,
  PrizesContainer,
  CardsContainer,
  DirectorContainer,
  PerksContainer,
  TradingContainer,
  PoolContainer,
} from "../containers";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <PrizesContainer />
        <CardsContainer />
        <DirectorContainer />
        <TradingContainer />
        <PerksContainer />
        <PoolContainer />
        <BadgesContainer />
        <HistoryContainer />
        <TryContainer />
        <RewardContainer />
        <UseContainer />
        <MintContainer />
        <StagesContainer />
        <PlansContainer />
        <StatsContainer />
        <LearnContainer />
        <GoalsContainer />
        <TeamContainer />
        <PartnersContainer />
        <FaqContainer />
        <CommunityContainer />
        <Footer />
      </main>
    </>
  );
}
